# Generated by Django 4.2.3 on 2023-07-30 07:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
